# Generated by Django 3.2.5 on 2021-07-26 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LoginPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendeduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('phone_no', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('reportFile', models.FileField(upload_to='')),
                ('aadhar', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('hSelectedName', models.CharField(default='Hospital not yet booked', max_length=200, null=True)),
                ('hBooked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
