# Generated by Django 3.2.5 on 2021-07-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0002_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='aadhar',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
