# Generated by Django 3.2.5 on 2021-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0004_auto_20210720_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='hSelectedCode',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='aadhar',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='age',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='phone_no',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
