# Generated by Django 3.2.5 on 2021-07-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0005_auto_20210722_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='aadhar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='hSelectedCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
