# Generated by Django 3.2.5 on 2021-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0006_auto_20210722_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='hSelectedCode',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='hSelectedName',
            field=models.CharField(default='Hospital not yet booked', max_length=200, null=True),
        ),
    ]
