# Generated by Django 3.2.5 on 2021-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginPage', '0007_auto_20210722_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='hBooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='reportFile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
