# Generated by Django 3.2.5 on 2021-07-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalDetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='hAddress',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='hBedBooked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='hName',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='hTotalNumBed',
            field=models.IntegerField(default=-1),
        ),
    ]
