# Generated by Django 3.2.5 on 2021-07-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalDetail', '0002_auto_20210718_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='hCity',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='hCode',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='hPincode',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='hospitaldetails',
            name='hState',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
