# Generated by Django 3.2.5 on 2021-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalDetail', '0003_auto_20210720_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='hLocation',
            field=models.URLField(default='NULL'),
        ),
    ]
