# Generated by Django 3.2.5 on 2021-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalDetail', '0004_hospitaldetails_hlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='hBedAvail',
            field=models.IntegerField(default=1),
        ),
    ]
